# Generated by Django 4.2.13 on 2024-06-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthyFoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=2345),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
